// <auto-generated />
using System;
using System.Collections.Generic;
using Aethera.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128195429_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdministrativeUnitType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AdministrativeUnit");

                    b.HasDiscriminator<string>("AdministrativeUnitType").HasValue("AdministrativeUnit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Alignment")
                        .HasColumnType("integer");

                    b.Property<int?>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<string>("BackstoryAndPersonality")
                        .HasColumnType("text");

                    b.Property<int?>("Class")
                        .HasColumnType("integer");

                    b.Property<string>("ClassFeatures")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeathSaveFailures")
                        .HasColumnType("integer");

                    b.Property<int?>("DeathSaveSuccesses")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DynastyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EquipedArmorId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("EquipmentProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long?>("ExperiencePoints")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feats")
                        .HasColumnType("text");

                    b.Property<int?>("HeroicInspirationCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HometownId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Initiative")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("LanguageProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PassivePerception")
                        .HasColumnType("integer");

                    b.Property<int?>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("SavingThrowProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SkillProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("Species")
                        .HasColumnType("integer");

                    b.Property<string>("SpeciesTraits")
                        .HasColumnType("text");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.Property<int?>("SubClass")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DynastyId");

                    b.HasIndex("FatherId");

                    b.HasIndex("HometownId");

                    b.HasIndex("MotherId");

                    b.HasIndex("Name");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Dynasty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Dynasties");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Religion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<int?>("Population")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RulerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettlementType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("RulerId");

                    b.ToTable("Settlements");

                    b.HasDiscriminator<string>("SettlementType").HasValue("Settlement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.Country", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit");

                    b.Property<Guid?>("RulerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SuzerainId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("Country");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.Province", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RulerId")
                        .HasColumnType("uuid");

                    b.ToTable("AdministrativeUnit", t =>
                        {
                            t.Property("RulerId")
                                .HasColumnName("Province_RulerId");
                        });

                    b.HasDiscriminator().HasValue("Province");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.Region", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RulerId")
                        .HasColumnType("uuid");

                    b.ToTable("AdministrativeUnit", t =>
                        {
                            t.Property("RulerId")
                                .HasColumnName("Region_RulerId");
                        });

                    b.HasDiscriminator().HasValue("Region");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Armor", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Items.Item");

                    b.Property<int?>("ArmorModifier")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Equipment", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Items.Item");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Weapon", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Items.Item");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Castle", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Settlements.Settlement");

                    b.HasDiscriminator().HasValue("Castle");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.City", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Settlements.Settlement");

                    b.HasDiscriminator().HasValue("City");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Village", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Settlements.Settlement");

                    b.HasDiscriminator().HasValue("Village");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Character", b =>
                {
                    b.HasOne("Aethera.Domain.Entities.Characters.Dynasty", null)
                        .WithMany()
                        .HasForeignKey("DynastyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Domain.Entities.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Domain.Entities.Settlements.Settlement", null)
                        .WithMany()
                        .HasForeignKey("HometownId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Domain.Entities.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Aethera.Domain.Entities.Basic.Dice", "HitDice", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Sides")
                                .HasColumnType("integer")
                                .HasColumnName("HitDice_DiceSides");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Charisma", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Modifier")
                                .HasColumnType("integer")
                                .HasColumnName("Charisma_Modifier");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Charisma_Score");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Constitution", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Modifier")
                                .HasColumnType("integer")
                                .HasColumnName("Constitution_Modifier");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Constitution_Score");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Dexterity", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Modifier")
                                .HasColumnType("integer")
                                .HasColumnName("Dexterity_Modifier");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Dexterity_Score");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Intelligence", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Modifier")
                                .HasColumnType("integer")
                                .HasColumnName("Intelligence_Modifier");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Intelligence_Score");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Strength", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Modifier")
                                .HasColumnType("integer")
                                .HasColumnName("Strength_Modifier");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Strength_Score");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Wisdom", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Modifier")
                                .HasColumnType("integer")
                                .HasColumnName("Wisdom_Modifier");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Wisdom_Score");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.HitPoints", "HP", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Current")
                                .HasColumnType("integer")
                                .HasColumnName("HP_Current");

                            b1.Property<int?>("Max")
                                .HasColumnType("integer")
                                .HasColumnName("HP_Maximum");

                            b1.Property<int?>("Temp")
                                .HasColumnType("integer")
                                .HasColumnName("HP_Temporary");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Charisma");

                    b.Navigation("Constitution");

                    b.Navigation("Dexterity");

                    b.Navigation("HP");

                    b.Navigation("HitDice");

                    b.Navigation("Intelligence");

                    b.Navigation("Strength");

                    b.Navigation("Wisdom");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Spell", b =>
                {
                    b.OwnsOne("Aethera.Domain.Entities.Basic.DiceExpression", "DamageAmount", b1 =>
                        {
                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConstantModifier")
                                .HasColumnType("integer")
                                .HasColumnName("Damage_ConstantModifier");

                            b1.Property<int>("DiceCount")
                                .HasColumnType("integer")
                                .HasColumnName("Damage_DiceCount");

                            b1.Property<int>("DiceSides")
                                .HasColumnType("integer")
                                .HasColumnName("Damage_DiceSides");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Basic.DiceExpression", "HealingAmount", b1 =>
                        {
                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConstantModifier")
                                .HasColumnType("integer")
                                .HasColumnName("Healing_ConstantModifier");

                            b1.Property<int>("DiceCount")
                                .HasColumnType("integer")
                                .HasColumnName("Healing_DiceCount");

                            b1.Property<int>("DiceSides")
                                .HasColumnType("integer")
                                .HasColumnName("Healing_DiceSides");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.Navigation("DamageAmount");

                    b.Navigation("HealingAmount");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Settlement", b =>
                {
                    b.HasOne("Aethera.Domain.Entities.AdministrativeUnits.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Domain.Entities.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("RulerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Weapon", b =>
                {
                    b.OwnsOne("Aethera.Domain.Entities.Basic.DiceExpression", "Damage", b1 =>
                        {
                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConstantModifier")
                                .HasColumnType("integer")
                                .HasColumnName("Weapon_ConstantModifier");

                            b1.Property<int>("DiceCount")
                                .HasColumnType("integer")
                                .HasColumnName("Weapon_DiceCount");

                            b1.Property<int>("DiceSides")
                                .HasColumnType("integer")
                                .HasColumnName("Weapon_DiceSides");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.Navigation("Damage");
                });
#pragma warning restore 612, 618
        }
    }
}
