// <auto-generated />
using System;
using System.Collections.Generic;
using Aethera.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aethera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228130254_UsersBase")]
    partial class UsersBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdministrativeUnitType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RulerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RulerId");

                    b.ToTable("AdministrativeUnit");

                    b.HasDiscriminator<string>("AdministrativeUnitType").HasValue("AdministrativeUnit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Dynasty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Motto")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Dynasties");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Religion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<int?>("Population")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RulerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettlementType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("RulerId");

                    b.ToTable("Settlements");

                    b.HasDiscriminator<string>("SettlementType").HasValue("Settlement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aethera.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Alignment")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Class")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeathSaveFailures")
                        .HasColumnType("integer");

                    b.Property<int?>("DeathSaveSuccesses")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DynastyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EquipedArmorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquipedWeaponId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ExperiencePoints")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HeroicInspirationCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HometownId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("LanguageProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("SavingThrowProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("SkillProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Species")
                        .HasColumnType("integer");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("SubClass")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DynastyId");

                    b.HasIndex("FatherId");

                    b.HasIndex("HometownId");

                    b.HasIndex("MotherId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Aethera.Infrastructure.Entities.CharacterTranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Culture")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityState")
                        .HasColumnType("integer");

                    b.Property<string>("Feats")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Culture")
                        .IsUnique();

                    b.ToTable("CharacterTranslations", (string)null);
                });

            modelBuilder.Entity("CharacterArmors", b =>
                {
                    b.Property<Guid>("ArmorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("ArmorId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterArmors");
                });

            modelBuilder.Entity("CharacterEquipments", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("CharacterEquipments");
                });

            modelBuilder.Entity("CharacterItems", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("CharacterSpells", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "SpellId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("CharacterWeapons", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("CharacterWeapons");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.Country", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit");

                    b.HasDiscriminator().HasValue("Country");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.Province", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit");

                    b.HasDiscriminator().HasValue("Province");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.Region", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit");

                    b.HasDiscriminator().HasValue("Region");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Armor", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Items.Item");

                    b.Property<int?>("ArmorModifier")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Equipment", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Items.Item");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Weapon", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Items.Item");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Castle", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Settlements.Settlement");

                    b.HasDiscriminator().HasValue("Castle");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.City", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Settlements.Settlement");

                    b.HasDiscriminator().HasValue("City");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Village", b =>
                {
                    b.HasBaseType("Aethera.Domain.Entities.Settlements.Settlement");

                    b.HasDiscriminator().HasValue("Village");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit", b =>
                {
                    b.HasOne("Aethera.Domain.Entities.AdministrativeUnits.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("RulerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Dynasty", b =>
                {
                    b.OwnsOne("Aethera.Domain.ValueObjects.Art", "Art", b1 =>
                        {
                            b1.Property<Guid>("DynastyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Art_FilePath");

                            b1.HasKey("DynastyId");

                            b1.ToTable("Dynasties");

                            b1.WithOwner()
                                .HasForeignKey("DynastyId");
                        });

                    b.Navigation("Art");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Characters.Spell", b =>
                {
                    b.OwnsOne("Aethera.Domain.Entities.Basic.DiceExpression", "DamageAmount", b1 =>
                        {
                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConstantModifier")
                                .HasColumnType("integer")
                                .HasColumnName("Damage_ConstantModifier");

                            b1.Property<int>("DiceCount")
                                .HasColumnType("integer")
                                .HasColumnName("Damage_DiceCount");

                            b1.Property<int>("DiceSides")
                                .HasColumnType("integer")
                                .HasColumnName("Damage_DiceSides");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Basic.DiceExpression", "HealingAmount", b1 =>
                        {
                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConstantModifier")
                                .HasColumnType("integer")
                                .HasColumnName("Healing_ConstantModifier");

                            b1.Property<int>("DiceCount")
                                .HasColumnType("integer")
                                .HasColumnName("Healing_DiceCount");

                            b1.Property<int>("DiceSides")
                                .HasColumnType("integer")
                                .HasColumnName("Healing_DiceSides");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.Navigation("DamageAmount");

                    b.Navigation("HealingAmount");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Item", b =>
                {
                    b.OwnsOne("Aethera.Domain.ValueObjects.Art", "Art", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Art_FilePath");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Art");
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Settlements.Settlement", b =>
                {
                    b.HasOne("Aethera.Domain.Entities.AdministrativeUnits.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("RulerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Aethera.Domain.ValueObjects.Art", "Art", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Art_FilePath");

                            b1.HasKey("SettlementId");

                            b1.ToTable("Settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.Navigation("Art");
                });

            modelBuilder.Entity("Aethera.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.HasOne("Aethera.Domain.Entities.Characters.Dynasty", null)
                        .WithMany()
                        .HasForeignKey("DynastyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Domain.Entities.Settlements.Settlement", null)
                        .WithMany()
                        .HasForeignKey("HometownId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Aethera.Domain.Entities.Basic.Dice", "HitDice", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Sides")
                                .HasColumnType("integer")
                                .HasColumnName("HitDice_DiceSides");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.HitPoints", "HP", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int?>("Current")
                                .HasColumnType("integer")
                                .HasColumnName("HP_Current");

                            b1.Property<int?>("Max")
                                .HasColumnType("integer")
                                .HasColumnName("HP_Maximum");

                            b1.Property<int?>("Temp")
                                .HasColumnType("integer")
                                .HasColumnName("HP_Temporary");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.ValueObjects.Art", "Art", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Art_FilePath");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Charisma", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Charisma_Score");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Constitution", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Constitution_Score");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Dexterity", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Dexterity_Score");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Intelligence", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Intelligence_Score");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Strength", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Strength_Score");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.OwnsOne("Aethera.Domain.Entities.Characters.AttributeScore", "Wisdom", b1 =>
                        {
                            b1.Property<Guid>("CharacterEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("Wisdom_Score");

                            b1.HasKey("CharacterEntityId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterEntityId");
                        });

                    b.Navigation("Art");

                    b.Navigation("Charisma")
                        .IsRequired();

                    b.Navigation("Constitution")
                        .IsRequired();

                    b.Navigation("Dexterity")
                        .IsRequired();

                    b.Navigation("HP");

                    b.Navigation("HitDice");

                    b.Navigation("Intelligence")
                        .IsRequired();

                    b.Navigation("Strength")
                        .IsRequired();

                    b.Navigation("Wisdom")
                        .IsRequired();
                });

            modelBuilder.Entity("Aethera.Infrastructure.Entities.CharacterTranslationEntity", b =>
                {
                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany("Translations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterArmors", b =>
                {
                    b.HasOne("Aethera.Domain.Entities.Items.Armor", null)
                        .WithMany()
                        .HasForeignKey("ArmorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterEquipments", b =>
                {
                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethera.Domain.Entities.Items.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterItems", b =>
                {
                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethera.Domain.Entities.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSpells", b =>
                {
                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethera.Domain.Entities.Characters.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterWeapons", b =>
                {
                    b.HasOne("Aethera.Infrastructure.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aethera.Domain.Entities.Items.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aethera.Domain.Entities.Items.Weapon", b =>
                {
                    b.OwnsOne("Aethera.Domain.Entities.Basic.DiceExpression", "Damage", b1 =>
                        {
                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConstantModifier")
                                .HasColumnType("integer")
                                .HasColumnName("Weapon_ConstantModifier");

                            b1.Property<int>("DiceCount")
                                .HasColumnType("integer")
                                .HasColumnName("Weapon_DiceCount");

                            b1.Property<int>("DiceSides")
                                .HasColumnType("integer")
                                .HasColumnName("Weapon_DiceSides");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.Navigation("Damage");
                });

            modelBuilder.Entity("Aethera.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
