export const LOADING_PHRASES_EN = [
  "Bribing the Dungeon Master with snacks...",
  "Polishing the mimic's teeth...",
  "Convincing the goblins that 'loading' isn't a curse...",
  "Reticulating splines... and dragon scales...",
  "Searching for the bard's lost dignity in the tavern...",
  "Feeding the server hamsters some high-quality oats...",
  "Trying to remember where the Necromancer hid the keys...",
  "Inflating the clouds over the Sword Coast...",
  "Teaching the skeletons how to do the thriller dance...",
  "Buffing the boss because you looked too confident...",
  "Casting 'Detect Lag' at level 9...",
  "Hiding all the bugs under a very large rug...",
  "Calculating the velocity of an unladen swallow...",
  "Wait, who invited the Gelatinous Cube to the party?",
  "Sorting loot by shininess...",
  "Apologizing to the NPCs for your previous playthrough...",
  "Gathering party members... Please wait for the Paladin to finish his prayer...",
  "Sharpening pixels for maximum sharpness...",
  "Consulting the Elder Gods (they are on a coffee break)...",
  "Ensuring the dragons are 100% science-based...",
  "Distracting the guards with a very suspicious cheese wheel...",
  "Loading terrain... Watch out for the 'Unfinished Geometry' pits!"
];

export const LOADING_PHRASES_UA = [
  "Підкуповуємо Майстра підземель смаколиками...",
  "Чистимо зуби міміку. Дуже обережно...",
  "Переконуємо гоблінів, що «завантаження» — це не прокляття...",
  "Шукаємо гідність барда у найближчій таверні...",
  "Годуємо серверних хом'яків відбірним вівсом...",
  "Намагаємося згадати, де некромант заховав ключі...",
  "Накачуємо хмари над узбережжям магічним ефіром...",
  "Вчимо скелетів танцювати гопак...",
  "Посилюємо боса, бо ви виглядаєте надто впевнено...",
  "Заклинання «Виявлення лагів» 9-го рівня...",
  "Ховаємо баги під дуже великий килим...",
  "Вираховуємо швидкість польоту ластівки без вантажу...",
  "Стривайте, а хто запросив Желатиновий Куб на вечірку?",
  "Сортуємо здобич за ступенем блиску...",
  "Перепрошуємо у NPC за вашу попередню гру...",
  "Збираємо загін... Зачекайте, поки Паладин закінчить молитву...",
  "Гостримо пікселі до магічного блиску...",
  "Консультуємося з Давніми Богами (у них зараз кава-брейк)...",
  "Відволікаємо вартових дуже підозрілим колом сиру...",
  "Завантажуємо ландшафт... Стережіться ям з «недоробленою геометрією»!",
  "Плетемо нитки долі... Головне, щоб не вийшов вузол...",
  "Перевіряємо, чи всі дракони сьогодні в доброму гуморі..."
];