/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/AdministrativeUnits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdministrativeUnitDto"][];
                        "application/json": components["schemas"]["AdministrativeUnitDto"][];
                        "text/json": components["schemas"]["AdministrativeUnitDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAdministrativeUnitCommand"];
                    "text/json": components["schemas"]["CreateAdministrativeUnitCommand"];
                    "application/*+json": components["schemas"]["CreateAdministrativeUnitCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Art/{entityType}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityType: components["schemas"]["EntityArtType"];
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CharacterPreview"][];
                        "application/json": components["schemas"]["CharacterPreview"][];
                        "text/json": components["schemas"]["CharacterPreview"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCharacterCommand"];
                    "text/json": components["schemas"]["CreateCharacterCommand"];
                    "application/*+json": components["schemas"]["CreateCharacterCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CharacterDetailDto"][];
                        "application/json": components["schemas"]["CharacterDetailDto"][];
                        "text/json": components["schemas"]["CharacterDetailDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Characters/equip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EquipItemCommand"];
                    "text/json": components["schemas"]["EquipItemCommand"];
                    "application/*+json": components["schemas"]["EquipItemCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Characters/{id}/dynasty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": string;
                    "text/json": string;
                    "application/*+json": string;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Characters/{id}/parents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SetParentsCommand"];
                    "text/json": components["schemas"]["SetParentsCommand"];
                    "application/*+json": components["schemas"]["SetParentsCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Characters/AddTranslation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddTranslationCommand"];
                    "text/json": components["schemas"]["AddTranslationCommand"];
                    "application/*+json": components["schemas"]["AddTranslationCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Dynasties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DynastyDto"][];
                        "application/json": components["schemas"]["DynastyDto"][];
                        "text/json": components["schemas"]["DynastyDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDynastyCommand"];
                    "text/json": components["schemas"]["CreateDynastyCommand"];
                    "application/*+json": components["schemas"]["CreateDynastyCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Dynasties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DynastyDto"];
                        "application/json": components["schemas"]["DynastyDto"];
                        "text/json": components["schemas"]["DynastyDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ItemDto"][];
                        "application/json": components["schemas"]["ItemDto"][];
                        "text/json": components["schemas"]["ItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateItemCommand"];
                    "text/json": components["schemas"]["CreateItemCommand"];
                    "application/*+json": components["schemas"]["CreateItemCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Item"];
                        "application/json": components["schemas"]["Item"];
                        "text/json": components["schemas"]["Item"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SettlementDto"][];
                        "application/json": components["schemas"]["SettlementDto"][];
                        "text/json": components["schemas"]["SettlementDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSettlementCommand"];
                    "text/json": components["schemas"]["CreateSettlementCommand"];
                    "application/*+json": components["schemas"]["CreateSettlementCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddTranslationCommand: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            feats?: string | null;
            backstory?: string | null;
            personality?: string | null;
        };
        AdministrativeUnitDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            type?: string | null;
            /** Format: uuid */
            rulerId?: string | null;
            /** Format: uuid */
            parentId?: string | null;
        };
        /** @enum {string} */
        AdministrativeUnitType: "Country" | "Region" | "Province";
        /** @enum {string} */
        Alignment: "LawfulGood" | "NeutralGood" | "ChaoticGood" | "LawfulNeutral" | "TrueNeutral" | "ChaoticNeutral" | "LawfulEvil" | "NeutralEvil" | "ChaoticEvil";
        /** @enum {string} */
        ArmorType: "Light" | "Medium" | "Heavy";
        Art: {
            readonly filePath?: string | null;
        };
        AttributeScore: {
            /** Format: int32 */
            score?: number;
            /** Format: int32 */
            readonly modifier?: number;
        };
        /** @enum {string} */
        CharacterClass: "Fighter" | "Wizard" | "Rogue" | "Cleric" | "Ranger" | "Paladin" | "Bard" | "Warlock" | "Sorcerer" | "Druid" | "Monk" | "Barbarian";
        CharacterDetailDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            species?: components["schemas"]["Species"];
            characterClass?: components["schemas"]["CharacterClass"];
            strengthScore?: components["schemas"]["AttributeScore"];
            dexterityScore?: components["schemas"]["AttributeScore"];
            constitutionScore?: components["schemas"]["AttributeScore"];
            intelligenceScore?: components["schemas"]["AttributeScore"];
            wisdomScore?: components["schemas"]["AttributeScore"];
            charismaScore?: components["schemas"]["AttributeScore"];
            /** Format: int32 */
            level?: number;
            /** Format: int64 */
            experiencePoints?: number | null;
            size?: components["schemas"]["Size"];
            alignment?: components["schemas"]["Alignment"];
            art?: components["schemas"]["Art"];
            /** Format: uuid */
            dynastyId?: string | null;
            /** Format: uuid */
            fatherId?: string | null;
            /** Format: uuid */
            motherId?: string | null;
            /** Format: uuid */
            hometownId?: string | null;
            /** Format: int32 */
            proficiencyBonus?: number | null;
            /** Format: int32 */
            initiative?: number | null;
            /** Format: int32 */
            armorClass?: number | null;
            /** Format: int32 */
            speed?: number | null;
            /** Format: int32 */
            passivePerception?: number | null;
            hp?: components["schemas"]["HitPoints"];
            hitDice?: components["schemas"]["Dice"];
            /** Format: int32 */
            deathSaveSuccesses?: number | null;
            /** Format: int32 */
            deathSaveFailures?: number | null;
            skillProficiencies?: components["schemas"]["Skill"][] | null;
            languageProficiencies?: components["schemas"]["Language"][] | null;
            feats?: string | null;
            /** Format: int32 */
            heroicInspirationCount?: number | null;
            backstory?: string | null;
            personality?: string | null;
            relatives?: components["schemas"]["RelativeDto"][] | null;
        };
        CharacterPreview: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            species?: components["schemas"]["Species"];
            class?: components["schemas"]["CharacterClass"];
            hp?: components["schemas"]["HitPoints"];
            /** Format: int32 */
            level?: number;
            art?: components["schemas"]["Art"];
            /** Format: uuid */
            dynastyId?: string | null;
        };
        CreateAdministrativeUnitCommand: {
            title?: string | null;
            type?: components["schemas"]["AdministrativeUnitType"];
            description?: string | null;
            /** Format: uuid */
            rulerId?: string | null;
            /** Format: uuid */
            parentId?: string | null;
        };
        CreateCharacterCommand: {
            name?: string | null;
            species?: components["schemas"]["Species"];
            class?: components["schemas"]["CharacterClass"];
        };
        CreateDynastyCommand: {
            name?: string | null;
            description?: string | null;
        };
        CreateItemCommand: {
            name?: string | null;
            description?: string | null;
            /** Format: int32 */
            weight?: number;
            /** Format: double */
            cost?: number;
            type?: components["schemas"]["ItemType"];
            damageExpression?: components["schemas"]["DiceExpression"];
            /** Format: int32 */
            armorModifier?: number | null;
            armorType?: components["schemas"]["ArmorType"];
        };
        CreateSettlementCommand: {
            title?: string | null;
            description?: string | null;
            /** Format: int32 */
            population?: number;
            type?: components["schemas"]["SettlementType"];
            /** Format: uuid */
            rulerId?: string | null;
            /** Format: uuid */
            provinceId?: string | null;
        };
        Dice: {
            /** Format: int32 */
            readonly sides?: number;
        };
        DiceExpression: {
            /** Format: int32 */
            readonly constantModifier?: number;
            /** Format: int32 */
            readonly diceCount?: number;
            /** Format: int32 */
            readonly diceSides?: number;
        };
        DynastyDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
            art?: components["schemas"]["Art"];
            motto?: string | null;
            /** Format: int32 */
            establishedYear?: number | null;
            /** Format: int32 */
            power?: number | null;
            status?: components["schemas"]["DynastyStatus"];
        };
        /** @enum {string} */
        DynastyStatus: "Ruling" | "Fallen" | "Vassal";
        /** @enum {string} */
        EntityArtType: "Character" | "Item" | "Settlement" | "Dynasty";
        /** @enum {string} */
        EntityState: "Updated" | "Disabled" | "Deleted";
        EquipItemCommand: {
            /** Format: uuid */
            characterId?: string;
            /** Format: uuid */
            itemId?: string;
        };
        HitPoints: {
            /** Format: int32 */
            max?: number | null;
            /** Format: int32 */
            current?: number | null;
            /** Format: int32 */
            temp?: number | null;
        };
        Item: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: date-time */
            readonly createdAt?: string | null;
            /** Format: date-time */
            readonly updatedAt?: string | null;
            /** Format: date-time */
            readonly deletedAt?: string | null;
            entityState?: components["schemas"]["EntityState"];
            name?: string | null;
            description?: string | null;
            /** Format: int32 */
            weight?: number | null;
            /** Format: double */
            cost?: number | null;
            art?: components["schemas"]["Art"];
        };
        ItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            type?: string | null;
            /** Format: double */
            cost?: number;
            art?: components["schemas"]["Art"];
        };
        /** @enum {string} */
        ItemType: "Item" | "Weapon" | "Armor" | "Equipment";
        /** @enum {string} */
        Language: "Common" | "Dwarvish" | "Elvish" | "Giant" | "Gnomish" | "Goblin" | "Halfling" | "Orcish" | "Abyssal" | "Celestial" | "Draconic" | "DeepSpeech" | "Infernal" | "Primordial" | "Sylvan" | "Undercommon";
        RelativeDto: {
            /** Format: uuid */
            id?: string;
            fullName?: string | null;
            role?: string | null;
            /** Format: uuid */
            fatherId?: string | null;
            /** Format: uuid */
            motherId?: string | null;
        };
        SetParentsCommand: {
            /** Format: uuid */
            characterId?: string;
            /** Format: uuid */
            fatherId?: string | null;
            /** Format: uuid */
            motherId?: string | null;
        };
        SettlementDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            type?: string | null;
            /** Format: int32 */
            population?: number;
            art?: components["schemas"]["Art"];
            /** Format: uuid */
            rulerId?: string | null;
            /** Format: uuid */
            provinceId?: string | null;
        };
        /** @enum {string} */
        SettlementType: "City" | "Castle" | "Village";
        /** @enum {string} */
        Size: "Tiny" | "Small" | "Medium" | "Large" | "Huge" | "Gargantuan";
        /** @enum {string} */
        Skill: "Acrobatics" | "AnimalHandling" | "Arcana" | "Athletics" | "Deception" | "History" | "Insight" | "Intimidation" | "Investigation" | "Medicine" | "Nature" | "Perception" | "Performance" | "Persuasion" | "Religion" | "SleightOfHand" | "Stealth" | "Survival";
        /** @enum {string} */
        Species: "Human" | "Elf" | "Dwarf" | "Halfling" | "Orc" | "Gnome" | "Tiefling" | "Dragonborn";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
